version: "1"

steps:
  - name: test
    image: python:3.7.0
    commands:
      - pip install pytest
      - pytest -v
    ruleset:
      event: [ push, pull_request ]
      branch: master

  - name: build-and-deploy-egg
    image: python:3.7.0
    commands:
      - echo '[distutils]'     >> ~/.pypirc
      - echo 'index-servers =' >> ~/.pypirc
      - echo '    tgt-python'  >> ~/.pypirc
      - echo '[tgt-python]'    >> ~/.pypirc
      - >
        echo 'repository: https://binrepo.target.com/artifactory/api/pypi/tgt-python' >> ~/.pypirc
      - echo "username:" $DOCKER_USERNAME >> ~/.pypirc
      - echo "password:" $DOCKER_PASSWORD >> ~/.pypirc
      - apt-get update
      - apt-get install postgresql software-properties-common freetds-bin freetds-common freetds-dev wget gcc g++ make zlibc zlib1g-dev openssl libssl-dev git -y
      - python ./setup.py install
      - python ./setup.py sdist upload --repository tgt-python
    secrets: [ docker_username, docker_password ]
    ruleset:
      event: push
      branch: master

secrets:
  - name: docker_username
    key: InfraServices-Storage/docker_username
    type: org
    engine: native

  - name: docker_password
    key: InfraServices-Storage/docker_password
    type: org
    engine: native

  - name: PLUGIN_SPEC_TOKEN
    key: api-platform/api-platform-team/plugin_spec_token
    type: shared
    engine: native